custom_gripper_controller:
    type: position_controllers/GripperActionController
    joint: gripper_finger1_joint
    action_monitor_rate: 100

gazebo_ros_control:
  pid_gains:
        gripper_finger1_joint: {p: 100, i: 0.0, d: 0.01} 
        gripper_finger2_joint: {p: 100, i: 0.0, d: 0.01} 
      
